### ISSUE TITLE
Data configuration is being logged twice

### ISSUE THREAD

**Issue by danderson00** [Azure/azure-mobile-apps-node#167]

**Comment by mamaso** [comment]
Mentioned this before, but the reason for this is the data provider being instantiated in the createContext & tableMiddleware (notification middleware has the same issue, but it doesn't log).

Have a some ideas to solve this: 
1. expose a create context middleware from the tableMiddleware & notificationMiddleware
2. add the relevant context to the object inside the table/notification middleware
3. have some DI where if a configuration.data.client exists, that client is used as the data module instead of creating a new one.

**Comment by danderson00** [comment]
The only initialisation should occur in the createContext middleware. The data provider should not be created anywhere else.
