### ISSUE TITLE
Content-Type header is case sensitive in parseItem middleware

### ISSUE THREAD

**Issue by aramkoukia** [Azure/azure-mobile-apps-node#368]
I'm trying out the Azure Mobile App API and getting an error on making Patch calls.

GET and POST and DELETE works fine.

Here is what my url looks like:

`PATCH http://mymobileappapi.azurewebsites.net/tables/Skill/c89027fa-edce-4d36-b42a-ecb0920ebab6`
body:

```
{
  "name": "Leadership SDFF"
}
```
I have these as headers too (as I said other http verbs work.)

```
ZUMO-API-VERSION 2.0.0
Content-Type Application/Json
```
And I get 500 error back with this in the body:

```
{
  "error": "An item to update was not provided"
}
```
The same id works when I do a GET using that id...

And when I make the same call using same body with PUT i get a 404 Not found without any content in the response body.

Any ideas?

**Comment by danderson00** [comment]
It turns out our implementation requires the content-type header value to be lower case, i.e. application/json works, whereas Application/Json doesn't. I've updated this issue to be the placeholder for the fix. As a workaround in the meantime, make the value for the content-type header lower case.

https://github.com/Azure/azure-mobile-apps-node/blob/master/src/express/middleware/parseItem.js#L27 should use req.get instead of req.headers. Keep in mind that values can also include encoding, e.g. application/json; charset=utf-8

**Comment by aramkoukia** [comment]
Yes, this fixes the issue, thanks for the quick turnaround.

**Comment by danderson00** [comment]
Resolved by https://github.com/Azure/azure-mobile-apps-node/commit/6cba43d40929d1c79bafecc99594a4f5602f7255
