### ISSUE TITLE
Inserting new property with null value should succeed with dynamic schema

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-mobile-apps-node#466]
If dynamic schema is on and a new record is inserted with a null value for a new property (that’s not already in the schema), then the Node.js server SDK throws an exception. Since dynamic schema is supposed to be used only during development time, it would be more useful to just ignore that property and log a warning.

**Comment by danderson00** [comment]
This is essentially due to dynamic schema not knowing what column type to create. It's fine to ignore these columns in a dynamic schema scenario, the columns will be created when data is provided in a subsequent insert.

**Comment by lindydonna** [comment]
@clancey Please add any additional comments you might have. Thanks!

**Comment by Clancey** [comment]
I would argue to mark this as a bug not a feature request.

As a first time user, I would install the mobile SDK into my app.  To test out azure, I would just create a simple object

```
public class Person
{
	public string FirstName {get;set;}
	public string MiddleName {get;set;}
	public string LastName {get;set;}
}
```

I then try and insert data using the mobile sdk.

```
\\Set everything up
var MobileService = new MobileServiceClient ("http://...");
var store = new MobileServiceSQLiteStore ("syncStore");
//Define my table
var personTable = MobileService.GetSyncTable<Person> ();
store.DefineTable<Person> ();

var person = new Person {FirstName = "James" LastName = "Clancey"};

//Insert the data
await personTable.InsertAsync (speaker);
await MobileService.SyncContext.PushAsync ();

```

That code will fail.  From a user standpoint I did everything perfect.  But the json that will submit will be

```
{
	"FirstName":"James",
	"MiddleName":null,
	"LastName":"Clancey"
}
```

This is extreemly frustrating and a horrible first run experience. Since the data is null for that column anyway you can safly ignore that column.

The other option would be transmit the data types/columns up from the GetSyncTable call. Since this is all in C# refection can be used to define the columns

```
//Define my table
var personTable = MobileService.GetSyncTable<Person> ();
```

**Comment by danderson00** [comment]
Yeh, fair call, the scenario is fairly clear. There are some differences in how the Javascript and JSON.NET serializers work - undefined properties in Javascript are omitted from the payload entirely. We'll address this on the server side, i.e. ignore columns with null values needing creation.

**Comment by danderson00** [comment]
@Clancey Haven't merged this yet, but you can test out the change by running `npm install danderson00/azure-mobile-apps-node#nullValues` or setting the azure-mobile-apps dependency in package.json to `"azure-mobile-apps": "danderson00/azure-mobile-apps-node#nullValues"`. We'll get it released shortly.

**Comment by danderson00** [comment]
Merged in, we'll release soon.
