### ISSUE TITLE
Skip() and Take() in Mobile Apps

### ISSUE THREAD

**Issue by mikejohanson** [Azure/azure-mobile-apps-node#480]
Hey Guys, 

I have a couple questions regarding how skip and take are working in the new Mobile Apps. 

1) I noticed ROW_NUMBER is now being returned as part of each item in the result set when using Skip() and Take(). Is there a way to turn this off? It causes problems when up you update a record from the list since row_number doesn't exist in the database. Simple workaround of course is to delete the property before sending back to the server to be updated, but since the previous version (mobile services) didn't do that I thought I'd call that out as something that has changed,

2) I noticed when using skip and take, lets say take(100),  I still only get 50 records back from the server despite the $top=100 in the query string due to the following line in parseQuery.js:

> context.query = context.query.take(Math.min(table.pageSize, req.query.$top));

I see that there is a pagesize property to be configured but...that seems like it updates the pagesize for all calls. Is there no longer a way for ONE call to take more than the default 50? 

Thanks for your help,
Mike

**Comment by adrianhall** [comment]
Hi Mike,

1) Can you give us an example?  Your table controller JS script and the output you are experiencing?  Also, confirm the version of the Node SDK you are using?  I've not experienced this myself, so I'd like to re-create the problem.

2) You set the maximum pageSize that the server will accept.  Your client can accept up to that number.  Offline sync will try to use as much as it can.  If you want to only bring 50 records back, use .Skip() and .Take(50).

**Comment by danderson00** [comment]
Hey @mikejohanson, 

Looks like SQLite is returning an extra column when take and / or skip are used. We'll fix this. This shouldn't happen when you use SQL Server as a data source.

With the page size, there is an option to specify page size from the client, but I can't remember the syntax, I'll dig it up tomorrow. Regardless, it looks from the code snippet you pasted that the server won't honor it anyway. I'll have to confirm, will get back to you tomorrow.

**Comment by mikejohanson** [comment]
Awesome, thanks!

**Comment by danderson00** [comment]
I got SQLite and SQL Server around the wrong way - SQL Server adds the ROW_NUMBER column when both skip and take are specified. I added a specific issue for this (https://github.com/Azure/azure-mobile-apps-node/issues/481), we'll get this out as soon as we can.

With page sizes, the logic for this is rather confusing. It is intended to prevent malicious users from requesting too many records and slowing the system down. Having said this, the logic is not quite right - it would make sense to set the maxTop setting to say 1000 and the pageSize to 50, and then explicitly requesting a $top of 100 should return 100 records, but the maximum top is restricted by the pageSize option. I'll have a chat about this logic with some colleagues and propose some changes to support this scenario.

In the meantime, you can increase the table.pageSize setting to allow more records to be retrieved, but this will affect queries that expect the lower pageSize value.

**Comment by danderson00** [comment]
Fixed the ROW_NUMBER column issue in https://github.com/Azure/azure-mobile-apps-node/pull/482. This is merged into the master branch but not released yet. Yet to discuss the page size logic - it's a bit more complex as it may result in a breaking change. Will keep you posted!

**Comment by mikejohanson** [comment]
Appreciate you help! 

In regards to what you're saying on page sizes, how you are describing that is exactly how I would think/expect it to work. It looks like changing line 40 in parseQuery.js to use max:

`context.query = context.query.take(Math.max(table.pageSize, req.query.$top));`

would address the issue since you already enforce the maxTop on line 28. So i'm gonna give this a shot locally and try it out for a while :)

**Comment by danderson00** [comment]
A colleague looked at this in a bit more detail and is fairly confident we can make this change. How did your investigation go?

With the ROW_NUMBER issue, SQL Server 2012 introduced the OFFSET and FETCH keywords that we can use here instead of the row numbering approach. Not sure if or when we'll get to this though - azure-odata-sql-js is a fairly old module that needs a fair bit of work - its future is a little uncertain. Anyway, the fix should resolve your issue, let us know if it is still causing problems.

**Comment by mikejohanson** [comment]
Haven't had a chance to test it a whole lot, but from what I have tested. It is working how I would expect. :)

**Comment by andreujuanc** [comment]
@danderson00  How is this going? I need to sync quite a few rows for some app, and 50 by 50 is very slow.  For now I will apply @mikejohanson fix (hope it works) but waiting for official fix.

**Comment by danderson00** [comment]
@andreujuanc Glad to hear the workaround fixed your issue. We're a bit stretched for resources at the moment, but I'll try to spend some time on this soon.

**Comment by danderson00** [comment]
I am looking at the documentation at https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-how-to-use-client-library#paging and https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-ios-how-to-use-client-library#a-namepagingahow-to-configure-page-size, and the Node.js backend doesn't behave like this.

It currently limits the page size to the server configured page size of 50, regardless of the client specified top parameter. I'm going to change this so that the server side `pageSize` option refers to the default page size if no top parameter is passed, and the maximum value for the top parameter is the server side `maxTop`.

We'll get this out in the next week or two.
