### ISSUE TITLE
Custom SQL Statement Error when INSERT IF NOT EXISTS

### ISSUE THREAD

**Issue by mauricionr** [Azure/azure-mobile-apps-node#486]
I'm trying to insert only if not exist, this is my query and i'm using `dynamicSchema = true`

```javascript
let query = {
        sql: `IF NOT EXISTS (SELECT * FROM table WHERE userId = @userId)
            BEGIN
                INSERT INTO table (userId, name, full_name, redeId, date)
                VALUES (@userId, @name, @full_name, @redeId, @date)
            END`,
        parameters: [
            { name: 'userId', value: item.userId },
            { name: 'name', value: item.name },
            { name: 'full_name', value: item.full_name },
            { name: 'redeId', value: item.redeId },
            { name: 'date', value: item.date },

        ]
    }

    context.data.execute(query)
        .then(function (createdObject) {
            res.status(201)
                .json(createdObject);
        })
        .catch(function (error) {
            console.log(error);
        })

```

I got this error
```logs
 { [RequestError: Cannot insert the value NULL into column 'id', table 'DB.dbo.table'; column does not allow nulls. INSERT fails.]
aplication-1   name: 'RequestError',
aplication-1   message: 'Cannot insert the value NULL into column \'id\', table \'DB.dbo.table\'; column does not allow nulls. INSERT fails.',
aplication-1   code: 'EREQUEST',
aplication-1   number: 515,
aplication-1   lineNumber: 3,
aplication-1   state: 2,
aplication-1   class: 16,
aplication-1   serverName: '{serverName}',
aplication-1   procName: '',
aplication-1   precedingErrors: [] }

```

Any ideia?

Thanks

**Comment by adrianhall** [comment]
The error message is quite clear.  The SDK assigns an GUID to the Id column in the normal course of operations.  You have to do it yourself if you are doing raw SQL calls.

**Comment by mauricionr** [comment]
thanks @adrianhall, any recommendation on this?

**Comment by adrianhall** [comment]
You can generate guids rather easily with standard node tools like[ the uuid package](https://www.npmjs.com/package/uuid).

**Comment by SteveALee** [comment]
@mauricionr  Did you try running that SQL directly against your database? Either in SQLServer, perhaps via Visual Studio tools, or SQLite?

I ask as that is unusual SQL style and may not work. SQL is declarative, not imperative, so you don't' write IF..THEN... style. Rather you need to think in terms of WHAT you want and WHEN. Then you'll have more joy with SQL, especially if you want your queries to be optimised.

Normally an update query would be of the form:

INSERT INTO table (<columns>)
   VALUES (<values>)
WHERE <condition>

See https://msdn.microsoft.com/en-us/library/ms174335.aspx

So in your case, something like:

INSERT INTO table (userId, name, full_name, redeId, date)
                VALUES (@userId, @name, @full_name, @redeId, @date)
WHERE NOT EXIST (SELECT * FROM table WHERE userId = @userId)

I'm not familiar with how the dynamic stuff works but from what @adrianhall says the userid is treated as the primary key and assigned by the SDK for you so it's always unique (rather than using the underlying DBs PK constraints)

Hope that helps. I know when I started with SQL I tried to write imperative code too. It requires a bit of a brain rewire at first (like functional or Reactive programming) but it can be very satisfying.
