### ISSUE TITLE
Remove dependency on Notification Hubs by stubbing the push endpoint

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-mobile-apps-node#507]
With the addition of the push endpoint and blade in Azure App Service, we no longer need the push registration endpoint and it can be deprecated.

**Comment by danderson00** [comment]
After thinking about this, I'm not sure we should remove it. It's actually very little code - we still need to provide the configuration mechanism and expose the NH client on the context object, so we end up removing a small piece of middleware and a page of code using the NH client, plus a few tests.

The advantage of having it there is that it facilitates local development - a big plus. The disadvantage is that we have to keep the API up to date with App Services push. Perhaps just providing a non-functional stub for local development might be the go.

**Comment by adrianhall** [comment]
I'm not sure we should be providing any configuration mechanism as it is overwriting something we are pushing into a cloud service.  The App Service Push is a very different configuration piece.  You would have to keep up to date with that - not the NH SDK.

Let's remove the push to a sample so that people who want to run it locally actually can see what is happening behind the scenes, but it isn't cluttering the main codebase.

**Comment by danderson00** [comment]
How is App Service push configured? I assumed app settings, but maybe not. The local configuration will never overwrite the Azure configuration as App Service hijacks the URL before it hits Mobile Apps.

We should provide some mechanism so that local development is still possible. Even if it is just a stub, that will stop the client from crashing.

**Comment by mikejohanson** [comment]
Hey Guys,

I saw issue #508 and Azure/azure-mobile-apps-net-server#170 , and I'm having the same error message as #508. However, I am running locally using v4.0.1 of the node SDK. I'm getting the error for both Xamarin.Droid and native iOS. Since I'm running locally I would imagine i would be using the "old style" given that i set the hubName and connectionString property in azuremobile.js. However, I'm not sure I exactly understand the resolution reading through both of those issues I referenced though. Am i supposed to be using invokeapi against this endpoint you guys are talking about in this issue to do the registration manually?

Thanks,
Mike

**Comment by adrianhall** [comment]
@mikejohanson This issue and #508 are not related.  The registration process for notification hubs has changed.  Open a different issue for your particular issue in the azure-mobile-apps-net-client repo.

**Comment by adrianhall** [comment]
@danderson00 I would suggest a stub that needs to be enabled, that just accepts an Installation and logs a message saying "In a deployed app, this would register the device (with some info like provided Installation JSON object)"  - i.e. we don't actually register; we only say it is registered.

**Comment by adrianhall** [comment]
Per #508 - let's stub out a push endpoint - accept the JSON payload and log it, but don't require the NH libraries.  

It should be enabled in azureMobile.js config and default should be off.

**Comment by adrianhall** [comment]
Removing Breaking Change label because we aren't changing the interface any more.

**Comment by danderson00** [comment]
@adrianhall There is another potential issue here - we expose the NH client on the req.azureMobile context object, and people may be using this to actually send pushes - App Service push doesn't expose this functionality.

We can still remove it and get people to configure a NH client manually, but I'm not sure this is something we want to do. Thoughts?

**Comment by adrianhall** [comment]
Let's just put an endpoint in that accepts anything (so the customer can move on in a local development setting), outputs an appropriate message and returns a valid response for the client.
