### ISSUE TITLE
Migration Azure Mobile Services to Azure Mobile App: UserId has changed

### ISSUE THREAD

**Issue by japf** [Azure/azure-mobile-apps-node#517]
Guys,

I'm having a serious issue while trying to migrate from Azure Mobile Service to Azure Mobile Apps. The issue is described with great details on StackOverflow: http://stackoverflow.com/questions/41212084/migration-azure-mobile-services-to-azure-mobile-app-userid-has-changed. Here is a copy/paste of the issue:

I'm facing an interesting challenge as I'm setting up a brand new instance of an Azure Mobile App connected to an existing DB of an existing Azure Mobile Services running in production.

The app running in production with AMS has Microsoft Account authentication and we filter user'data server-side using the context.userid field. This field looks like MicrosoftAccount:abcdef....

After setting up a new Azure Mobile App with Microsoft authentication support, I'm getting a userId that is different, something like sid:ABC...

Using the documentation, I was able to get more details about user identity using the getIdentity() api:

context.user.getIdentity().then((data) => { });

But I'm still unable to find the "old" UserId that was used in the AMS world... and therefore I cannot have link between the existing data and the new app.

Any idea ?

**Comment by adrianhall** [comment]
Unfortunately, the "people that know" are on vacation over the holiday period, and won't be back until January.  The issue has something to do with how Microsoft Account handles multiple endpoints - basically there is a difference between the AMS version and AMA version.  However, I wanted to get the right answer for you rather than guessing.  Once the right people get back from vacation, I'll follow up.

**Comment by japf** [comment]
@adrianhall great, I will put that on hold until January.

**Comment by japf** [comment]
@adrianhall any update on this question ? Thanks !

**Comment by mattchenderson** [comment]
It sounds like you're doing an SDK upgrade rather than a migration (we distinguish between those terms since the migration between hosting environments is an automatic process).
I think you'll want to be looking at the upgrade documentation ([.NET](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-net-upgrading-from-mobile-services), [Node.JS](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-node-backend-upgrading-from-mobile-services)).

Specifically, you'll want to look at the [authentication considerations](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-net-upgrading-from-mobile-services#a-nameauthenticationaauthentication-considerations) section, which is apparently only in the .NET topic. @adrianhall - can we look at getting the equivalent section updated in Node? The concepts should be the same.

The general idea of the problem is that MSA registrations don't allow multiple redirect URLs on different domains. That means each of these apps (the new and existing one) would need a separate registration. User IDs happen to be scoped to the registration, so you won't have an immutable ID which is shared by the two applications. You could use a value like email as a bridge for the upgrade process, but be aware that the user could change this in their account settings.

**Comment by adrianhall** [comment]
Will do.

**Comment by japf** [comment]
Thaks @mattchenderson for the follow-up. My idea was to do an SDK upgrade and keep the existing AMS in place during the transition. I don't want to break anything as the app is live in production is thousand of active users... I was a big afraid about the idea of pressing the "Migrate" button :-)

In the database today, I don't have emails or anything else, only the "old" UserId. That's was the recommended option back at the AMS time.

Do I have any way to configure the auth on the new services to reuse the auth of the AMS app so that I can have the same id ? What would you do if you were me ;-) ?

**Comment by adrianhall** [comment]
There isn't a really good answer for you, unfortunately.  Per the referenced documents, this is inherent in the MSA authentication scheme.   Anything we suggest means losing access to the existing provider.

I'd do a hard switch and adjust the redirect URI in the MSA, leaving the users to upgrade as necessary.  It's the least painful of the approaches.
