### ISSUE TITLE
FOR JSON PATH doesn't work with api

### ISSUE THREAD

**Issue by NinoDLC** [Azure/azure-mobile-apps-node#545]
SQL code : 
```
SELECT (
	JSON_QUERY(
		(
		SELECT foo.id AS [Foo]
		FROM   foo 
		WHERE  foo.id = 'bar' 
		FOR JSON PATH, ROOT('Foos') 
		), '$')
	)
```
Node.js api code : 
```
var api = {
    // an example of executing a SQL statement directly
    get: (request, response, next) => {
        var query = {
            sql: "SELECT (JSON_QUERY((SELECT foo.id AS [Foo] FROM foo	WHERE foo.id = @bar FOR JSON PATH, ROOT('Foos')), '$'))",
            parameters: [
                { name: 'bar', value: request.query.bar}
            ]
        };

        request.azureMobile.data.execute(query)
            .then(function (results) {
                response.json(results);
            });
    }
};

module.exports = api;
```

And the result is : 
```
[ 
   { '' : '{\"Foos\":[{\"QcmID\":\"7EED5396-9151-4E3D-BCBF-FDB72CDD22B7\"}]}' 
   } 
]
```

The result of the query is put inside an empty double quote value (an empty json object), and its value (the actual result we should simply get) is encoded in it.

**Comment by elamalani** [comment]
@NinoDLC Thanks for using Azure Mobile Apps. Please look at the GitHub readme where we talk about the [future of Azure Mobile Apps](https://github.com/Azure/azure-mobile-apps-node#future-of-azure-mobile-apps). At this time, we will only look at fixing critical issues in the product. 

I'll close this issue since it's a few months old but let us know if you have any questions. Thanks!
